<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIwoltcy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIwoltcy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIwoltcy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIwoltcy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIwoltcy\appDevDebugProjectContainer([
    'container.build_hash' => 'Iwoltcy',
    'container.build_id' => '8a8573a8',
    'container.build_time' => 1579342467,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIwoltcy');
