<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYee1n3c\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYee1n3c/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYee1n3c.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYee1n3c\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYee1n3c\appProdProjectContainer([
    'container.build_hash' => 'Yee1n3c',
    'container.build_id' => '434b822d',
    'container.build_time' => 1591471960,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYee1n3c');
