<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKcegbei\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKcegbei/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKcegbei.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKcegbei\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKcegbei\appProdProjectContainer([
    'container.build_hash' => 'Kcegbei',
    'container.build_id' => 'a279c648',
    'container.build_time' => 1579167025,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKcegbei');
